name: deo_emerges_example
description: Example app for Deo Emerges package
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  deo_emerges:
    path: ../
  provider: ^6.1.2
  flutter_bloc: ^9.1.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true