name: deo_emerges
description: Flutter networking package built on Dio with concurrent requests, error handling, and state management integration.
version: 0.1.3
homepage: https://github.com/Tisankan/deo_emerges
repository: https://github.com/Tisankan/deo_emerges
issue_tracker: https://github.com/Tisankan/deo_emerges/issues
documentation: https://github.com/Tisankan/deo_emerges/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  logger: ^2.5.0
  crypto: ^3.0.6
  retry: ^3.1.2
  meta: ^1.15.0
  riverpod: ^2.6.1
  provider: ^6.1.2
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  test: ^1.24.0
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.example.deo_emerges
        pluginClass: DeoEmergesPlugin
      ios:
        pluginClass: DeoEmergesPlugin