name: deo_emerges
description: An advanced Flutter networking package built on top of Dio, offering concurrent request handling, comprehensive error management, and extensive features for modern Flutter applications.
version: 0.1.0
homepage: https://github.com/yourusername/deo_emerges
repository: https://github.com/yourusername/deo_emerges
issue_tracker: https://github.com/yourusername/deo_emerges/issues
documentation: https://github.com/yourusername/deo_emerges/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  logger: ^2.0.1
  crypto: ^3.0.3
  retry: ^3.1.2
  meta: ^1.9.1
  riverpod: ^2.3.10
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  test: ^1.24.3
  build_runner: ^2.4.6

flutter:
  # This section identifies this Flutter package as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift etc.)
  # which should be registered in the plugin registry.
  plugin:
    platforms:
      android:
        package: com.example.deo_emerges
        pluginClass: DeoEmergesPlugin
      ios:
        pluginClass: DeoEmergesPlugin